// AUTO-GENERATED by scripts/generate-gallery.mjs. Do not edit by hand.
// Lists the images in public/gallery so the rotating gallery picks up new
// photos on each build. Re-run: npm run gallery:manifest

export interface GalleryImage {
  file: string
  alt: string
}

export const galleryImages: GalleryImage[] = [
  {
    "file": "linkedin_post-2.jpg",
    "alt": "ZettaMine, Linkedin Post 2"
  }
]
