// Scans public/gallery and writes app/data/gallery.ts so the rotating gallery
// picks up new photos on each build. Wired into pre-dev / pre-build hooks in
// package.json, so publishing a new photo is just: drop the file in the folder
// and rebuild. Re-run manually with: npm run gallery:manifest
import { readdirSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { join, dirname, extname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const galleryDir = join(root, 'public', 'gallery')
const outFile = join(root, 'app', 'data', 'gallery.ts')

const exts = new Set(['.jpg', '.jpeg', '.png', '.webp', '.avif', '.gif'])

function pretty(file) {
  const name = basename(file, extname(file))
  return (
    name
      .replace(/[-_]+/g, ' ')
      .replace(/\b\w/g, (c) => c.toUpperCase())
      .trim() || 'ZettaMine'
  )
}

let files = []
if (existsSync(galleryDir)) {
  files = readdirSync(galleryDir)
    .filter((f) => exts.has(extname(f).toLowerCase()))
    .sort()
}

const items = files.map((f) => ({ file: f, alt: `ZettaMine, ${pretty(f)}` }))

const header =
  '// AUTO-GENERATED by scripts/generate-gallery.mjs. Do not edit by hand.\n' +
  '// Lists the images in public/gallery so the rotating gallery picks up new\n' +
  '// photos on each build. Re-run: npm run gallery:manifest\n'

const body =
  'export interface GalleryImage {\n' +
  '  file: string\n' +
  '  alt: string\n' +
  '}\n\n' +
  `export const galleryImages: GalleryImage[] = ${JSON.stringify(items, null, 2)}\n`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, header + '\n' + body)
console.log(`generate-gallery: wrote ${items.length} image(s) to app/data/gallery.ts`)
